spring:
  application:
    name: ledger
  datasource:
    url: jdbc:postgresql://localhost:5432/ledger
    username: postgres
    password: 9d/Byte
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port:8080

jwt:
  secret: BC7nAq0s+9a8HRWJG6tgZjIhQKQlu82g6yMYCL4OU14=
  expiration: 86400000
